### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
@adil192, there is a little problem. We need to specify multiple variations of strings "Move $n notes" and "$n notes will be renamed" for different intervals of $n.

For Czech it is:
> Move $n notes

`1`: Přesunout 1 poznámku
`2--4`: Přesunout $n poznámky
`5+`: Přesunout $n poznámek

> $n notes will be renamed

`1`: Bude přejmenována 1 poznámka
`2--4`: Budou přejmenovány $n poznámky
`5+`: Bude přejmenováno $n poznámek

**Comment by adil192** [comment]
We'll now only need the `5+` intervals :)

**Comment by ceskyDJ** [comment]
I'm sorry, but I didn't get it. Could you describe it in more detail, please?

**Comment by adil192** [comment]
The 2 strings you mentioned will only be used if there are 5 or more notes

**Comment by ceskyDJ** [comment]
Ah, ok. Nice, thanks!

**Comment by ceskyDJ** [comment]
So, it's ready to merge :D.

**Pull request merged**
