### PR TITLE
snap: add gstreamer libraries

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Comment by adil192** [comment]
We may also need `libgstreamer-plugins-base1.0-dev` for ogg support, but I'm not sure if that's necessary here?

**Comment by soumyaDghosh** [comment]
> We may also need `libgstreamer-plugins-base1.0-dev` for ogg support, but I'm not sure if that's necessary here?

The libraries are in the runtime sdk, but the pkgconfig and development files got removed in the sdk, thus the need of these files. So, we need files mostly to satisfy the build. I'll try to look into it once again.

**Comment by adil192** [comment]
Please mark this as "ready for review" when you're ready

**Comment by adil192** [comment]
I'll just merge this for now to try and get builds working

**Pull request merged**
