### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Oh, it was so many hard strings for translation :D. I hope I translated it well in a minimum of mistakes.

Btw, good job with redoing of the login process!

**Comment by ceskyDJ** [comment]
> `almostDone(OUTDATED): "Almost ready for syncing, tap to finish logging in"`

Btw, I don't know it's clear. They are two information in one sentence. I tried to translated as well as I can but I don't know it's well-understandable. Maybe the English version is a little unclear to me, too. Could you reform it a bit, please?

**Comment by ceskyDJ** [comment]
> `connectedTo(OUTDATED): Připojeno k`

What is this string related to?

**Comment by adil192** [comment]
> > `almostDone(OUTDATED): "Almost ready for syncing, tap to finish logging in"`

This is shown when the user has logged in to their Nextcloud account but hasn't entered their encryption password yet. Does this help?



> > `connectedTo(OUTDATED): Připojeno k`
> 
> What is this string related to?

The "Connected to" text comes before the server url on the profile page:

image

**Comment by ceskyDJ** [comment]
> This is shown when the user has logged in to their Nextcloud account but hasn't entered their encryption password yet. Does this help?

Hmm, ok. So, let's merge it. This is a thing I need to see "in person" and try to play with it for some time. I think it's pretty good right now, so maybe just a few fixes will come later. Are you ok with that?

**Comment by ceskyDJ** [comment]
Ok, I added translation of the current note refreshing settings option, so it really should be ready for merge. Of course, as I noted in my last comment, it probably need some final touches but they will come in the (I hope near) future.

**Comment by adil192** [comment]
> I think it's pretty good right now, so maybe just a few fixes will come later. Are you ok with that?

Of course, thanks!

**Pull request merged**
